### GET userinfo
GET http://localhost:5001/connect/userinfo
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0OTQwOUQ1QjE4QzYwMjM1MzcxRjA0RDhEN0M2N0U5IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEiLCJuYmYiOjE3MjEzMDc2MzEsImlhdCI6MTcyMTMwNzYzMSwiZXhwIjoxNzIxMzExMjMxLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEvcmVzb3VyY2VzIiwic2NvcGUiOlsib3BlbmlkIiwiZW1haWwiLCJwcm9maWxlIl0sImFtciI6WyJwd2QiXSwiY2xpZW50X2lkIjoibWFrZS1tb25leSIsInN1YiI6IjEiLCJhdXRoX3RpbWUiOjE3MjEzMDc2MzEsImlkcCI6ImxvY2FsIiwic2lkIjoiM0FDQ0I5MDIzOTk1MzlCQjQ4MkZFMjNFMjJGRjdGNTgiLCJqdGkiOiI0OTFDOERDRUZBOTRFRDM3RDYxMzgwM0E0MzJDNjRGRCJ9.V4FgBsOor8BndUnbehVm1DnAVla1oczfC3tyDHgDW-_kaiV2TysN0sZglKrSC1aOgSzKHhjOiIwyyz8frhx3NBNXezymT1x6Sbk0Z2Y5I5QmNfuNlk32QxQiRBxt1E2zia6TrUf6mvnlgVl48CZGqN8zAnorNsyIK9GroB_v5Cr6JiS0do2T65oEULgudPpMuVydVly_boXQzs4ZW7wMSG7QzZkbItyXZ6EUQ6tf9ICvNnFN-VU97UyNYNm1cTlCWCYnhsP146IeyNiQA0pJsHzwoa1Eorr9_O2zC8TqQa5J7qdGbYgFMhyo2PO7D1MtR8UfYTuaLfV-RTiSQao-Vw

###